my_final_project/products/models.py
from my_final_project import db
from dataclasses import dataclass

@dataclass
class Product(db.Model):

    id: int
    name: str
    internal_code: str
    customer_code: str


    id = db.Column(db.Integer, primary_key=True)
    internal_code = db.Column(db.String, unique=True, nullable=False)
    customer_code = db.Column(db.String, unique=True, nullable=False)
    name = db.Column(db.String, unique=True, nullable=False)

    category_id = db.Column(db.Integer, db.ForeignKey('product_category.id'))
    production_line_id = db.Column(db.Integer, db.ForeignKey('production_line.id'))

    category = db.relationship('ProductCategory', backref=db.backref('products', lazy='dynamic'))
    prod_line = db.relationship('ProductionLine', backref=db.backref('products', lazy='dynamic'))
    def __repr__(self) -> str:
        return f"{self.name}"

@dataclass
class ProductCategory(db.Model):

    __tablename__ = 'product_category'

    id: int
    name: str

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, unique=True, nullable=False)

    def __repr__(self) -> str:
        return f"{self.name}"

@dataclass
class ProductionLine(db.Model):
    __tablename__ = 'production_line'

    id: int
    name: str

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, unique=True, nullable=False)

    def __repr__(self) -> str:
        return f"{self.name}"

my_final_project/products/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField
from wtforms.validators import DataRequired


class ProductForm(FlaskForm):
    
    name = StringField('Product Name', validators=[DataRequired()])
    internal_code = StringField('Internal Code', validators=[DataRequired()])
    customer_code = StringField('Customer Code', validators=[DataRequired()])
    category_id = SelectField(choices=[])
    production_line_id = SelectField(choices=[])


class ProductCategoryForm(FlaskForm):
    name= StringField('Category Name', validators=[DataRequired()])

my_final_project/products/views.py
from flask import render_template, Blueprint, redirect, request, url_for
from .models import Product, ProductCategory, ProductionLine
from .forms import ProductForm
from my_final_project import db

bp = Blueprint('products', __name__, template_folder='templates', url_prefix='/')

@bp.route('/')
def main():
    return render_template('product-main.html')

@bp.route('/product_list')
def product_list():
    products = Product.query.all()
    return render_template('product-list.html', products=products)


@bp.route('/add_product', methods=['GET', 'POST'])
def add_product():
    categories = ProductCategory.query.all()
    production_lines = ProductionLine.query.all()
    CATEGORIES = [(category.id, category.name) for category in categories]
    PRODUCTION_LINES = [(line.id, line.name) for line in production_lines]
    form = ProductForm()
    form.category_id.choices = CATEGORIES
    form.production_line_id.choices = PRODUCTION_LINES
    error = None
    if form.validate_on_submit():
        
        
        product = Product(
            name=form.name.data,
            customer_code=form.customer_code.data,
            internal_code=form.internal_code.data,
            category_id=form.category_id.data)
            
        db.session.add(product)
        db.session.commit()
        print(form.category_id.data)
        return redirect(url_for('products.product_list'))

    return render_template('product-add.html', form=form)


# @bp.get('/edit_product/<int:id>')
# def edit_product(id):
#     categories = ProductCategory.query.all()
#     CATEGORIES = [(category.id, category.name) for category in categories]
#     form = ProductForm()
#     form.category_id.choices = CATEGORIES
#     product = Product.query.filter_by(id=id).first()

#     form.name.data = product.name
#     form.customer_code.data = product.customer_code
#     form.internal_code.data = product.internal_code
#     form.category_id.data = product.category_id
#     return render_template('product-add.html', form=form)

# @bp.post('/edit_product/<int:id>')
# def edit_products(id):
#     categories = ProductCategory.query.all()
#     CATEGORIES = [(category.id, category.name) for category in categories]
#     form = ProductForm()
#     form.category_id.choices = CATEGORIES
#     product = Product.query.filter_by(id=id).first()
#     if form.validate_on_submit():

#         product.name = form.name.data
#         product.customer_code = form.customer_code.data
#         product.internal_code = form.internal_code.data
#         product.category_id = form.category_id.data
#         db.session.commit()
#         return redirect(url_for('products.product_list'))
#     return redirect(url_for('products.product_list'))

@bp.route('/edit_product/<int:id>', methods=['GET','POST'])
def edit_product(id):
    product = Product.query.filter_by(id=id).first()
    categories = ProductCategory.query.all()
    production_lines = ProductionLine.query.all()
    PRODUCTION_LINES = [(line.id, line.name) for line in production_lines]
    CATEGORIES = [(category.id, category.name) for category in categories]
    product = Product.query.filter_by(id=id).first()
    form = ProductForm(
        category_id=product.category_id,
        production_line_id=product.production_line_id
    )
    form.category_id.choices = CATEGORIES
    form.production_line_id.choices = PRODUCTION_LINES
    

    if form.validate_on_submit():
        product.name = form.name.data
        product.customer_code = form.customer_code.data
        product.internal_code = form.internal_code.data
        product.category_id = form.category_id.data
        product.production_line_id = form.production_line_id.data
        db.session.commit()
        return redirect(url_for('products.product_list'))
    if request.method == 'GET':

        form.name.data = product.name
        form.customer_code.data = product.customer_code
        form.internal_code.data = product.internal_code
        form.category_id.default = product.category_id
        form.production_line_id.default = product.production_line_id
        return render_template('product-add.html', form=form)

    return redirect(url_for('products.product_list'))    

@bp.route('/delete_product/<int:id>', methods=['POST', 'GET'])
def delete_product(id):
    product = Product.query.filter_by(id=id).first()
    db.session.delete(product)
    db.session.commit()
    return redirect(url_for('products.product_list'))

my_final_project/products/templates/product-add.html
{% extends 'base.html' %}

{% block content %}


<form method="POST">
    {{ form.csrf_token }}
    
    {{ form.internal_code.label }} {{ form.internal_code(size=20) }}
    {{ form.customer_code.label }} {{ form.customer_code(size=20) }}
    {{ form.name.label }} {{ form.name(size=20) }}
    {{ form.category_id.label }} {{ form.category_id }}
    {{ form.production_line_id.label }} {{ form.production_line_id}}
    <input type="submit" value="Submit">
</form>
{% if error %}
    <p>{{error}}</p>
{% endif %}
{% endblock content %}

my_final_project/products/templates/product-edit.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {{ form.csrf_token }}
    {{ form.name.label }} {{ form.name(size=20) }}
    <input type="submit" value="Go">
</form>
{% if error %}
    <p>{{error}}</p>
{% endif %}
{% endblock content %}

my_final_project/products/templates/product-list.html
{% extends 'base.html' %}

{% block content %}
<table class="table" id="products">
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Internal Code</th>
            <th scope="col">Customer Code</th>
            <th scope="col">Description</th>
        </tr>
    </thead>
    <tbody>
    {% for product in products %}
    <tr>
        <td><a href="{{ url_for('products.edit_product', id=product.id) }}">{{ product.id }}</a></td>
        <td>{{ product.internal_code }}</td>
        <td>{{ product.customer_code }}</td>
        <td>{{ product.name }}</td>
        
        <td><a href="{{ url_for('products.delete_product', id=product.id) }}">Delete</a></td>
    </tr>
        
    {% endfor %}
    </tbody>
</table>

{% endblock content %}

my_final_project/products/templates/product-main.html
{% extends 'base.html' %}
{% block content %}
    <h1>Products</h1>
{% endblock content %}<h1>Products</h1>